import PDFDocument from 'pdfkit';
import { Response } from 'express';

export class PdfUtils {

  /* =========================
     TABLE HELPERS
  ========================== */

  private static drawTableHeader(
    doc: PDFDocument,
    y: number,
    headers: string[],
    columnX: number[],
    columnWidths: number[]
  ) {
    doc.font('Helvetica-Bold').fontSize(11);

    for (const [index, header] of headers.entries()) {
      doc.text(header, columnX[index], y, {
        width: columnWidths[index],
      });
    }

    doc
      .moveTo(50, y + 18)
      .lineTo(550, y + 18)
      .strokeColor('#000')
      .stroke();
  }

  private static drawTableRow(
    doc: PDFDocument,
    y: number,
    row: string[],
    columnX: number[],
    columnWidths: number[]
  ): number {
    doc.font('Helvetica').fontSize(10);

    let maxRowHeight = 0;

    // First calculate max row height
    for (const [index, cell] of row.entries()) {
      const textHeight = doc.heightOfString(cell, {
        width: columnWidths[index],
      });

      if (textHeight > maxRowHeight) {
        maxRowHeight = textHeight;
      }
    }

    // Then draw cells
    for (const [index, cell] of row.entries()) {
      doc.text(cell, columnX[index], y, {
        width: columnWidths[index],
        lineBreak: true,
      });
    }

    // Row separator
    doc
      .moveTo(50, y + maxRowHeight + 6)
      .lineTo(550, y + maxRowHeight + 6)
      .strokeColor('#ddd')
      .stroke();

    return maxRowHeight + 10;
  }

  /* =========================
     TUTORS PDF
  ========================== */

  static generateTutorsPdf(tutors: any[], res: Response) {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      'attachment; filename="all-tutors.pdf"'
    );

    doc.pipe(res);

    /* ===== HEADER ===== */

    doc.fontSize(20).text('All Tutors Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(
      `Generated on: ${new Date().toLocaleDateString()}`,
      { align: 'right' }
    );
    doc.text(`Total Tutors: ${tutors.length}`, { align: 'right' });

    doc.moveDown(2);

    /* ===== TABLE CONFIG ===== */

    const columnX = [50, 140, 260, 360, 450];
    const columnWidths = [80, 110, 80, 70, 70];
    const headers = ['Name', 'Email', 'PhoneNumber', 'Status', 'Joined'];

    let y = doc.y + 10;

    PdfUtils.drawTableHeader(doc, y, headers, columnX, columnWidths);
    y += 28;

    for (const tutor of tutors) {

      if (y > 730) {
        doc.addPage();
        y = 80;
        PdfUtils.drawTableHeader(doc, y, headers, columnX, columnWidths);
        y += 28;
      }

      const rowHeight = PdfUtils.drawTableRow(
        doc,
        y,
        [
          tutor.tutorDetail?.name || 'N/A',
          tutor.email || 'N/A',
          tutor.phoneNumber || 'N/A',
          tutor.status || 'N/A',
          tutor.createdAt
            ? new Date(tutor.createdAt).toLocaleDateString()
            : 'N/A'
        ],
        columnX,
        columnWidths
      );

      y += rowHeight;
    }

    /* ===== FOOTER ===== */

    const footerY = doc.page.height - 60;

    doc
      .fontSize(9)
      .fillColor('#555')
      .text('Generated by System', 50, footerY, {
        align: 'center',
        width: 500
      });

    doc.end();
  }

  /* =========================
     USERS PDF
  ========================== */

  static generateUsersPdf(users: any[], res: Response) {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      'attachment; filename="all-users.pdf"'
    );

    doc.pipe(res);

    /* ===== HEADER ===== */

    doc.fontSize(20).text('All Users Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(
      `Generated on: ${new Date().toLocaleDateString()}`,
      { align: 'right' }
    );
    doc.text(`Total Users: ${users.length}`, { align: 'right' });

    doc.moveDown(2);

    /* ===== TABLE CONFIG ===== */

    const columnX = [50, 170, 320, 420, 480];
    const columnWidths = [110, 130, 90, 60, 60];
    const headers = ['Name', 'Email', 'Phone', 'Status', 'Joined'];

    let y = doc.y + 10;

    PdfUtils.drawTableHeader(doc, y, headers, columnX, columnWidths);
    y += 28;

    for (const user of users) {

      if (y > 730) {
        doc.addPage();
        y = 80;
        PdfUtils.drawTableHeader(doc, y, headers, columnX, columnWidths);
        y += 28;
      }

      const rowHeight = PdfUtils.drawTableRow(
        doc,
        y,
        [
          user.userDetail?.name || 'N/A',
          user.email || 'N/A',
          user.phoneNumber || 'N/A',
          user.status || 'N/A',
          user.createdAt
            ? new Date(user.createdAt).toLocaleDateString()
            : 'N/A'
        ],
        columnX,
        columnWidths
      );

      y += rowHeight;
    }

    /* ===== FOOTER ===== */

    const footerY = doc.page.height - 60;

    doc
      .fontSize(9)
      .fillColor('#555')
      .text('Generated by System', 50, footerY, {
        align: 'center',
        width: 500
      });

    doc.end();
  }
}
